BankKata/Controllers/DepositsController.cs
using System.Web.Mvc;
using BankKata.Models;

namespace BankKata.Controllers
{
    public class DepositsController : Controller
    {
        private readonly IAccountTransactions _accountTransactions;

        public DepositsController(IAccountTransactions accountTransactions)
        {
            _accountTransactions = accountTransactions;
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: Deposits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Account account)
        {
            account.Date = new Clock().Now();

            account.Balance = _accountTransactions.GetAccountBalance(account.Amount);
            
            if (ModelState.IsValid)
            {
                var transaction = account.ToStatementFormat();

                _accountTransactions.SaveTransaction(transaction);

                return RedirectToAction("Index", "AccountBalance");
            }

            return View(account);
        }
    }
}

BankKata/Controllers/WithdrawsController.cs
using System.Web.Mvc;
using BankKata.Models;

namespace BankKata.Controllers
{
    public class WithdrawsController : Controller
    {
        private readonly IAccountTransactions _accountTransactions;

        public WithdrawsController(IAccountTransactions accountTransactions)
        {
            _accountTransactions = accountTransactions;
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: Withdraws/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Account account)
        {
            account.Date = new Clock().Now();

            account.Balance = _accountTransactions.GetAccountBalance(-account.Amount);

            if (ModelState.IsValid)
            {
                var transaction =  account.ToStatementFormat();

                _accountTransactions.SaveTransaction(transaction);

                return RedirectToAction("Index", "AccountBalance");
            }

            return View(account);
        }
    }
}

BankKata/Views/Deposits/Create.cshtml
@model BankKata.Models.Account

@{
    ViewBag.Title = "New Deposit";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AccountTransactions</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "AccountBalance")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BankKata/Views/Deposits/Index.cshtml
@model IEnumerable<BankKata.Models.AccountBalance>

@{
    ViewBag.Title = "On Screen Balance";
}

<h2>On Screen Balance</h2>

<p>
    @Html.ActionLink("Create New Deposit", "Create")
</p>
<p>
    @Html.ActionLink("Create New Withdraw", "Create", "Withdraws")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Balance)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Balance)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new {id = item.AccountBalanceId}) |
            @Html.ActionLink("Details", "Details", new {id = item.AccountBalanceId}) |
            @Html.ActionLink("Delete", "Delete", new {id = item.AccountBalanceId})
        </td>*@
    </tr>
}

</table>