BankKata/Controllers/AccountBalanceController.cs
using System.Web.Mvc;
using System.Windows.Forms;
using BankKata.Investiment;
using BankKata.Models;

namespace BankKata.Controllers
{
	public class AccountBalanceController : Controller
	{
	    private readonly IStatementReader _statementReader;

	    public AccountBalanceController(IStatementReader statementReader)
	    {
	        _statementReader = statementReader;
	    }
        public ActionResult Index()
        {
            return View(_statementReader.ReadAccountStatement());
        }

	    public ActionResult DisplayStatement()
	    {
	        MessageBox.Show(_statementReader.CreateStatement());
            
	        return RedirectToAction("Index");
	    }
    }
}

BankKata/Controllers/DepositsController.cs
using System.Web.Mvc;
using BankKata.Models;

namespace BankKata.Controllers
{
    public class DepositsController : Controller
    {
        private readonly IAccountTransactions _accountTransactions;

        public DepositsController(IAccountTransactions accountTransactions)
        {
            _accountTransactions = accountTransactions;
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: Deposits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Account account)
        {
            account.Date = new Clock().Now();

            account.Balance = _accountTransactions.GetAccountBalance(account.Amount);
            
            if (ModelState.IsValid)
            {
                var transaction = account.ToStatementFormat();

                _accountTransactions.SaveTransaction(transaction);

                return RedirectToAction("Index", "AccountBalance");
            }

            return View(account);
        }
    }
}

BankKata/Controllers/WithdrawController.cs
using System.Web.Mvc;
using BankKata.Models;

namespace BankKata.Controllers
{
    public class WithdrawController : Controller
    {
        private readonly IAccountTransactions _accountTransactions;
        private readonly ISendMessage _sendMessage;

        public WithdrawController(IAccountTransactions accountTransactions, ISendMessage sendMessage)
        {
            _accountTransactions = accountTransactions;
            _sendMessage = sendMessage;
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: Withdraws/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Account account)
        {
            account.Date = new Clock().Now();

            account.Balance = _accountTransactions.GetAccountBalance(-account.Amount);

            if (ModelState.IsValid)
            {
                var transaction =  account.ToStatementFormat();

                _accountTransactions.SaveTransaction(transaction);

                _sendMessage.Send(account);

                return RedirectToAction("Index", "AccountBalance");
            }

            return View(account);
        }
    }
}

BankKata/Views/AccountBalance/Index.cshtml
@model IEnumerable<BankKata.Models.Account>

@{
    ViewBag.Title = "On Screen Balance";
}

<h2>On Screen Balance</h2>

<p>
    @Html.ActionLink("Create New Deposit", "Create", "Deposits")
</p>
<p>
    @Html.ActionLink("Create New Withdraw", "Create", "Withdraw")
</p>
<p>

    <div class="form-group">
        <input type="submit" value="Print Statement" class="btn btn-default" onclick="location.href = '@Url.Action("DisplayStatement", "AccountBalance")'"/>
    </div>
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Balance)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Balance)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new {id = item.AccountTransactionsId}) |
            @Html.ActionLink("Details", "Details", new {id = item.AccountTransactionsId}) |
            @Html.ActionLink("Delete", "Delete", new {id = item.AccountTransactionsId})
        </td>*@
    </tr>
}

</table>